In [59]:
#web scrapping
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [6]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1',headers = headers).text

In [7]:
soup = BeautifulSoup(webpage,'lxml')

In [20]:
soup.find_all('div',class_='companyCardWrapper__primaryInformation')[1]

<div class="companyCardWrapper__primaryInformation"><div class="companyCardWrapper__companyLogo"><img alt="Accenture logo" height="50" loading="lazy" onerror="this.onerror=null;this.src='/static/icons/company-placeholder.svg';" src="https://static.ambitionbox.com/assets/v2/images/rs:fit:200:200:false:false/aHR0cHM6Ly9tZWRpYS5uYXVrcmkuY29tL21lZGlhL2FiY29tcGxvZ28vYWNjZW50dXJlLW9yaWdpbmFsLmpwZw.webp" width="50"/></div> <div class="companyCardWrapper__metaInformation"><div class="companyCardWrapper__header"><div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName companyCardWrapper__companyName--m8"><h2 class="companyCardWrapper__companyName" title="Accenture">
								Accenture
							</h2></a> <!-- --></div> <button arialabel="Follow" class="companyCardWrapper__FollowCTA g-btn g-btn--text g-btn--md" title="Follow" type="button"><!-- --> <span class="g-btn__label g-btn__label--md g-btn__label--text g-btn__label--loader">Follow</span> <!-- --></button> <!-- --></div> <div class="companyCardWrapper__ratingWrapper"><div class="companyCardWrapper__companyRatingWrapper"><div class="companyCardWrapper__companyRating"><div class="rating_star_container"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#9acd32" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;padding-bottom:1px;">
			3.7<!-- --></div></div></div></div> <span class="companyCardWrapper__companyRatingCount">
									(67.9k)
								</span></div> <span class="companyCardWrapper__interLinking">
								IT Services &amp; Consulting | Bangalore / Bengaluru +245 other locations
							</span> <!-- --> <div class="companyCardWrapper__ratingComparisonWrapper"><!-- --> <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div> <span class="companyCardWrapper__ratingValues">Promotions / Appraisal, Salary &amp; Benefits, Work Satisfaction</span></div></div></div> <div class="viewSalaryInsights"><div class="salaryInsightsText">To view salary insights</div> <div class="designationSelectionText">
							Select designation
						</div></div> <!-- --></div></div>

In [23]:
soup.find_all('h2')

[<h2 class="companyListing__title">
 							Companies in India
 						</h2>,
 <h2 class="companyCardWrapper__companyName" title="TCS">
 								TCS
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="Accenture">
 								Accenture
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="Wipro">
 								Wipro
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="Cognizant">
 								Cognizant
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="Capgemini">
 								Capgemini
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="HDFC Bank">
 								HDFC Bank
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="Infosys">
 								Infosys
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="ICICI Bank">
 								ICICI Bank
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="HCLTech">
 								HCLTech
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="Tech Mahindra">
 								Tech Mahindra
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="Genpact">
 								Genpact
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="Teleperformance">
 								Teleperformance
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="Axis Bank">
 								Axis Bank
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="Concentrix Corporation">
 								Concentrix Corporation
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="Jio">
 								Jio
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="Amazon">
 								Amazon
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="iEnergizer">
 								iEnergizer
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="Reliance Retail">
 								Reliance Retail
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="IBM">
 								IBM
 							</h2>,
 <h2 class="companyCardWrapper__companyName" title="LTIMindtree">
 								LTIMindtree
 							</h2>]

In [25]:
for i in soup.find_all('h2'):
    print(i.text.strip())

Companies in India
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
ICICI Bank
HCLTech
Tech Mahindra
Genpact
Teleperformance
Axis Bank
Concentrix Corporation
Jio
Amazon
iEnergizer
Reliance Retail
IBM
LTIMindtree

In [48]:
soup.find_all('div',class_='rating_star_container')[0].text.strip()

'3.4'

In [46]:
soup.find_all('span',class_='rating_star_container')

[]

In [32]:
company = soup.find_all('div',class_='companyCardWrapper')

In [34]:
len(company)

20

In [53]:
names = []
ratings = []
reviews = []

for i in company:
    names.append(i.find('h2').text.strip())
    ratings.append(i.find('div',class_='rating_star_container').text.strip())
    reviews.append(i.find('span',class_='companyCardWrapper__ActionCount').text.strip())
    
d = {"name":names,"rating":ratings,"reviews":reviews}

df = pd.DataFrame(d)

In [54]:
df

                      name rating reviews
0                      TCS    3.4    1.1L
1                Accenture    3.7   67.9k
2                    Wipro    3.7   60.9k
3                Cognizant    3.7   57.8k
4                Capgemini    3.7   49.5k
5                HDFC Bank    3.8   47.9k
6                  Infosys    3.5   45.5k
7               ICICI Bank    4.0   43.6k
8                  HCLTech    3.4   42.6k
9            Tech Mahindra    3.4   40.8k
10                 Genpact    3.6     39k
11         Teleperformance    3.8     35k
12               Axis Bank    3.7   30.9k
13  Concentrix Corporation    3.6   30.3k
14                     Jio    4.3   29.6k
15                  Amazon    4.0   29.4k
16              iEnergizer    4.6   26.8k
17         Reliance Retail    3.9     26k
18                     IBM    3.9   24.6k
19             LTIMindtree    3.6   24.2k

In [70]:
# we will create the final dataframe
final = pd.DataFrame()

for j in range(1,11):
    url = 'https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page={}'.format(j)
    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    webpage = requests.get(url,headers = headers).text
    
    soup = BeautifulSoup(webpage,'lxml')
    
    company = soup.find_all('div',class_='companyCardWrapper')
    
    names = []
    ratings = []
    reviews = []

    for i in company:
        names.append(i.find('h2').text.strip())
        ratings.append(i.find('div',class_='rating_star_container').text.strip())
        reviews.append(i.find('span',class_='companyCardWrapper__ActionCount').text.strip())
        
    d = {"name":names,"rating":ratings,"reviews":reviews}

    final = pd.concat([final, df], ignore_index=True)   # ✅ append to final DataFrame

In [71]:
final

                            name rating reviews
0                     John Deere    4.0    3.8k
1    HDFC Ergo General Insurance    3.9    3.8k
2                      Oyo Rooms    3.1    3.8k
3           Jindal Steel Limited    3.9    3.8k
4                       DCB Bank    3.8    3.8k
..                           ...    ...     ...
195             Publicis Sapient    3.4    3.6k
196             American Express    4.1    3.6k
197                       Subros    3.8    3.6k
198                      Viatris    4.1    3.6k
199          Pidilite Industries    4.2    3.6k

[200 rows x 3 columns]