In [1]:
import numpy as np
import pandas as pd 

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('Titanic-Dataset.csv',usecols=['Age','Pclass','Fare','Survived'])

In [3]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [4]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [5]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [10]:
X_train.tail()

     Pclass   Age      Fare
534       3  30.0    8.6625
584       3   NaN    8.7125
493       1  71.0   49.5042
527       1   NaN  221.7792
168       1   NaN   25.9250

In [16]:
knn = KNNImputer(n_neighbors=3,weights='distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [17]:
pd.DataFrame(X_train_trf,columns=X_train.columns).tail()

     Pclass        Age      Fare
707     3.0  30.000000    8.6625
708     3.0  26.959410    8.7125
709     1.0  71.000000   49.5042
710     1.0  32.666667  221.7792
711     1.0  49.762895   25.9250

In [18]:
lr = LogisticRegression()

lr.fit(X_train_trf,y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.7039106145251397

In [ ]:
# Comparison with Simple Imputer --> mean

si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [20]:
lr = LogisticRegression()

lr.fit(X_train_trf2,y_train)

y_pred2 = lr.predict(X_test_trf2)

accuracy_score(y_test,y_pred2)

0.6927374301675978