In [2]:
import numpy as np
import pandas as pd

In [3]:
food_data = pd.read_csv('food.csv')

In [4]:
food_data

      Name Gender     City Frequency     Item   Spends
0   Nitish      M  Kolkata    Weekly    Burger      11
1      Anu      F  Gurgaon     Daily  Sandwich      14
2    Mukku      M  Kolkata      Once      Vada      25
3     Suri      M  Kolkata   Monthly     Pizza      56
4    Rajiv      M    Patna     Never    Paneer      34
5   Nitish      M  Kolkata    Weekly    Burger      11
6      Anu      F  Gurgaon     Daily  Sandwich      14
7    Mukku      M  Kolkata      Once      Vada      25
8     Suri      M  Kolkata   Monthly     Pizza      56
9    Rajiv      M    Patna     Never    Paneer      34
10  Nitish      M  Kolkata    Weekly    Burger      11
11     Anu      F  Gurgaon     Daily  Sandwich      14
12   Mukku      M  Kolkata      Once      Vada      25
13    Suri      M  Kolkata   Monthly     Pizza      56
14   Rajiv      M    Patna     Never    Paneer      34
15  Nitish      M  Kolkata    Weekly    Burger      11
16     Anu      F  Gurgaon     Daily  Sandwich      14
17   Mukku      M  Kolkata      Once      Vada      25
18    Suri      M  Kolkata   Monthly     Pizza      56
19   Rajiv      M    Patna     Never    Paneer      34
20  Nitish      M  Kolkata    Weekly    Burger      11
21     Anu      F  Gurgaon     Daily  Sandwich      14
22   Mukku      M  Kolkata      Once      Vada      25
23    Suri      M  Kolkata   Monthly     Pizza      56
24   Rajiv      M    Patna     Never    Paneer      34
25  Nitish      M  Kolkata    Weekly    Burger      11
26     Anu      F  Gurgaon     Daily  Sandwich      14
27   Mukku      M  Kolkata      Once      Vada      25
28    Suri      M  Kolkata   Monthly     Pizza      56
29   Rajiv      M    Patna     Never    Paneer      34
30  Nitish      M  Kolkata    Weekly    Burger      11
31     Anu      F  Gurgaon     Daily  Sandwich      14
32   Mukku      M  Kolkata      Once      Vada      25
33    Suri      M  Kolkata   Monthly     Pizza      56
34   Rajiv      M    Patna     Never    Paneer      34
35  Nitish      M  Kolkata    Weekly    Burger      11
36     Anu      F  Gurgaon     Daily  Sandwich      14
37   Mukku      M  Kolkata      Once      Vada      25
38    Suri      M  Kolkata   Monthly     Pizza      56
39   Rajiv      M    Patna     Never    Paneer      34
40  Nitish      M  Kolkata    Weekly    Burger      11
41     Anu      F  Gurgaon     Daily  Sandwich      14
42   Mukku      M  Kolkata      Once      Vada      25
43    Suri      M  Kolkata   Monthly     Pizza      56
44   Rajiv      M    Patna     Never    Paneer      34
45  Nitish      M  Kolkata    Weekly    Burger      11
46     Anu      F  Gurgaon     Daily  Sandwich      14
47   Mukku      M  Kolkata      Once      Vada      25
48    Suri      M  Kolkata   Monthly     Pizza      56
49   Rajiv      M    Patna     Never    Paneer      34

In [7]:
food_data.pivot_table(index='City', columns= 'Item ', values='Spends', aggfunc='mean')

Item     Burger  Paneer  Pizza  Sandwich  Vada
City
Gurgaon     NaN     NaN    NaN      14.0   NaN
Kolkata    11.0     NaN   56.0       NaN  25.0
Patna       NaN    34.0    NaN       NaN   NaN

In [8]:
print(food_data.columns)

Index(['Name', 'Gender', 'City', 'Frequency', 'Item ', 'Spends'], dtype='object')